#!/usr/bin/env bash

# Check if the script is running on web-01 or web-02
if [[ $(hostname) == *-web-01 ]]; then
    server_name="03-web-01"
elif [[ $(hostname) == *-web-02 ]]; then
    server_name="03-web-02"
else
    echo "This script should only be run on web-01 or web-02."
    exit 1
fi

# Update packages
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to add the custom HTTP header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $server_name;' /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration
sudo systemctl restart nginx
